{
  imports = [
    ./ai
    ./audio.nix
    ./core.nix
    ./desktop.nix
    ./dev
    ./fonts.nix
    ./gaming
    ./graphics.nix
    ./locale.nix
    ./media.nix
    ./networking.nix
    ./nix-settings.nix
    ./office.nix
    ./packages.nix
    ./theme.nix
    ./users.nix
    ./virtualisation.nix
    ./zen-browser.nix
  ];
}
